### ISSUE TITLE
Cargo Dependency: rtsp-types default branch

### ISSUE THREAD

**Issue by maxlueerprivate** [sdroege/rtsp-server#31]
I tried to build the rtsp-server with an older cargo version, but it fails because the default branch of the dependency rtsp-types was changed to 'main'. In older Cargo Versions, Cargo tries to pull repos with the default branch master which does not exist anymore.

This can easily be fixed by changing line 18 in `Cargo.toml` to:

`rtsp-types = { git = "https://github.com/sdroege/rtps-types.git", branch = "main" }`

I would be very pleased, if this will be fixed. Thx :)

**Comment by sdroege** [comment]
Ah sure, I didn't know about that cargo limitation. Do you want to send a PR for that small change?

**Comment by maxlueerprivate** [comment]
> Ah sure, I didn't know about that cargo limitation. Do you want to send a PR for that small change?

Done :)
